version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mern
  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
    - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - users
    networks:
      - mern
  auth:
    build: ./auth-service
    container_name: auth
    depends_on:
      - mongo
    environment:
      PORT: 5000
      DB_URL: mongodb://mongo:27017/auth-db
      JWT_SECRET: this_is_a_secret
    networks:
      - mern
  users:
    build: ./user-service
    container_name: users
    depends_on:
      - mongo
    environment:
      PORT: 5000
      DB_URL: mongodb://mongo:27017/user-db
      AUTH_URL: http://auth:5000/api/auth/verify
    networks:
      - mern
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8081:80
    environment:
      API_URL: http://web:8080
    depends_on:
      - web
    networks:
      - mern
networks:
  mern:
    driver: bridge